#!/bin/bash

MODULE_PATH="./node_modules"
REBUILD_PATH="$MODULE_PATH/.bin/electron-rebuild"
PREBUILT_PATH="$MODULE_PATH/electron-prebuilt"
PACKAGE_JSON_PATH="$PREBUILT_PATH/package.json"

function json_value {
  # From https://gist.github.com/cjus/1047794
  cat $1 | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w $2 | tr ": " " "
}

ELECTRON_VERSION=($( json_value $PACKAGE_JSON_PATH "version" ))
ELECTRON_VERSION=${ELECTRON_VERSION[1]}

echo "Electron Version: $ELECTRON_VERSION"

npm install
$REBUILD_PATH --version "$ELECTRON_VERSION" --electron-prebuilt-dir "$PREBUILT_PATH" --module-dir "$MODULE_PATH"
